name: Build and Push Docker Image

on: [push, pull_request]

env:
  DOCKER_USERNAME: youchen0620
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +'%Y%m%d-%H%M')
        docker build -t ${DOCKER_USERNAME}/2025cloud:${IMAGE_TAG} .

    - name: Push image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +'%Y%m%d-%H%M')
        docker push ${DOCKER_USERNAME}/2025cloud:${IMAGE_TAG}